# Generated by Django 3.2.6 on 2023-12-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_paciente', models.CharField(max_length=20)),
                ('documento_doctor', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('enfermedad', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
